### ISSUE TITLE
Editing Reqirements Page According to Customer Feedback

### ISSUE THREAD

**Issue by sumeyrayilmaz-zz** [bounswe/bounswe2019group10#20]
Actions:
1.  Glossary part will be added.
1.  Requirements will be editted according to customer feedback.
Deadline : 01.03.19, 23.59

**Comment by yavuzDemir21** [comment]
About 1.3.3.1 if anyone can look, please enlighten me I couldnt quite catch what should we do

**Comment by yavuzDemir21** [comment]
about search part i don't know what to do, I think one who wrote the search part should edit it.

**Comment by sumeyrayilmaz-zz** [comment]
I edited the notification part under the system requirements as 2.6 so I thought we can keep 1.3.3.1 as a user requirement. Feedback says we should define them but I think as they are mentioned in 2.6 it is not a problem anymore.

**Comment by sumeyrayilmaz-zz** [comment]
I thought the search part is about grammar mistakes . I edited it as it seems more meaningful.

**Comment by sumeyrayilmaz-zz** [comment]
Do you have any idea about why Cihat said set a specific meeting time? We set it before and there is an issue about it.

**Comment by fahricansanli** [comment]
In our communication plan, we hadn't specified  a specific time for our weekly meetings. I edited that part and specified our weekly meeting as on Mondays 7pm as agreed.
