### ISSUE TITLE
Updating requirements on wiki

### ISSUE THREAD

**Issue by MelihDemir99** [bounswe/bounswe2019group10#200]
Updates required due to feedback.

Deadline: 18.11.2019

**Comment by muratbuldu** [comment]
1.2.1.2 should be updated.
1.1.3 should be updated. Users can see the progress of any other user.

1.2.2.1 should be updated.

1.3.3.1 should be updated.

1.5.1 should be updated.

4.1 should be updated.

**Comment by sumeyrayilmaz-zz** [comment]
requirements edited according to customer feedback and weekly meeting.
