### ISSUE TITLE
Improvements after feedback

### ISSUE THREAD

**Issue by fahricansanli** [bounswe/bounswe2019group10#25]
Action:
1. All groups will read the feedback and update their scenarios and mockups accordingly.
Deadline: 12.03.19  23.59

**Comment by muratbuldu** [comment]
User scenario one is updated according to the feedback.

**Comment by hsnbsrbalaban** [comment]
Third scenario and its mockup is updated according to the feedback.

**Comment by sumeyrayilmaz-zz** [comment]
All scenarios and mockups are updated.
