### ISSUE TITLE
Missing features in frontend

### ISSUE THREAD

**Issue by muratbuldu** [bounswe/bounswe2019group10#269]
In courses:
language remove lang
history push to main after language add 
change active language

In header:
double click on search icon
Users with no language

In search:
click listeners for search results

In profile:
visual bug collapsing fields

**Comment by muratbuldu** [comment]
Writing reducer:
forgets previous states

**Comment by hsnbsrbalaban** [comment]
In profile page:
after editing is done, done button is not updating

**Comment by muratbuldu** [comment]
click listeners for search results

**Comment by muratbuldu** [comment]
language and search related bugs were resolved

**Comment by muratbuldu** [comment]
profile page was updated to remove collapsed parts

**Comment by muratbuldu** [comment]
In home page
add writing list, update quiz list

**Comment by burak-tepedelen** [comment]
writing reducer fixed and home page displays are added
