### ISSUE TITLE
Creating sequence diagrams

### ISSUE THREAD

**Issue by fahricansanli** [bounswe/bounswe2019group10#27]
Assignees should examine the class diagram and use case diagram, then create at least one sequence diagram.

**Comment by fahricansanli** [comment]
@sumeyra-yilmaz-2015400129 @muratbuldu @hsnbsrbalaban  you can add one sequence diagram, if you want

**Comment by sumeyrayilmaz-zz** [comment]
Murat Buldu, Melih Demir, Sümeyra Yılmaz and Emre Yılmaz will add one sequence diagram.

**Comment by sumeyrayilmaz-zz** [comment]
Yavuz Demir, Kaan Dura, Nevzat Ersoy and Fahri Can Şanlı will update sequence diagrams.

**Comment by sumeyrayilmaz-zz** [comment]
I added a sequence diagram of chat.

**Comment by yavuzDemir21** [comment]
If everyone is done with this we should close this issue once and for all
