### ISSUE TITLE
Updating Class Diagram

### ISSUE THREAD

**Issue by sumeyrayilmaz-zz** [bounswe/bounswe2019group10#29]
Action Items:
1. Class diagram will be updated as determined at the meeting.
Deadline 22.03.19, 23.59

**Comment by fahricansanli** [comment]
The edits discussed during the meeting are done.

**Comment by muratbuldu** [comment]
Classes are linked to each other

**Comment by fahricansanli** [comment]
@sumeyra-yilmaz-2015400129 and I did the final editions.
