### ISSUE TITLE
Update annotation response

### ISSUE THREAD

**Issue by muratbuldu** [bounswe/bounswe2019group10#303]
Update creator field to an object like
"creator": {
    "id": "http://example.org/user1",
    "type": "Person",
    "name": "My Pseudonym",
    "nickname": "pseudo",
  }
Add date field.

https://www.w3.org/TR/annotation-model/

**Comment by yavuzDemir21** [comment]
I am on it, I will transform creator part like this.

**Comment by yavuzDemir21** [comment]
I will also add created date, updated date too.
