### ISSUE TITLE
Language Endpoint Bug Report

### ISSUE THREAD

**Issue by fahricansanli** [bounswe/bounswe2019group10#318]
"/lang/unsubs" has returning error as response. You can find the error below.
{
    "timestamp": "2019-12-12T13:54:08.314+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "could not deserialize; nested exception is org.hibernate.type.SerializationException: could not deserialize",
    "path": "/lang/unsubs"
}

**Comment by selim-karaduman** [comment]
Yes, this is being fixed right now.

**Comment by selim-karaduman** [comment]
The problem should be fixed. Check the corresponding commit of the fix: https://github.com/bounswe/bounswe2019group10/commit/eceea8197868b27ccd864b448c9edd8cbe759222
