### ISSUE TITLE
Requirements and Mockups

### ISSUE THREAD

**Issue by fahricansanli** [bounswe/bounswe2019group10#34]
Adding requirements and mockups of our project to the report

**Comment by fahricansanli** [comment]
The deadline is 30.03.2019

**Comment by fahricansanli** [comment]
I will be adding requirements part to the report and Basri will add mockups.

**Comment by fahricansanli** [comment]
Requirements are added to the report

**Comment by hsnbsrbalaban** [comment]
Mockups and Use Cases Diagram are added to the report
