### ISSUE TITLE
Accessing Member Profiles

### ISSUE THREAD

**Issue by burak-tepedelen** [bounswe/bounswe2019group10#372]
Getting access to a member's profile requires memberId but we don't have access to writing evaluators memberId only username. Need a /member/{username} in member-controller.

**Comment by yavuzDemir21** [comment]
Is this really requires a new endpoint or what @selim-karaduman  is about to do will accomplish this task also?

**Comment by yavuzDemir21** [comment]
either way I am going to do what you asked.
