### ISSUE TITLE
Update date field in create annotation endpoint

### ISSUE THREAD

**Issue by muratbuldu** [bounswe/bounswe2019group10#381]
Create annotation endpoint uses a different time zone. I created an annotation at 16.18 but it showed 19.18.

Please update date assignment.

**Comment by yavuzDemir21** [comment]
I was aware of that issue and worked on it but couldnt solved. Now I have tried a db level solution hope it works.

**Comment by yavuzDemir21** [comment]
Now it works perfectly!

**Comment by yavuzDemir21** [comment]
It wasn't done :( Problem still continues, there was a little miscommunication

**Comment by muratbuldu** [comment]
Handled in frontend
